### ISSUE TITLE
Can't stop loading after pressing one of Examples in web-app.

### ISSUE THREAD

**Issue by kencyke** [exoego/scala-js-ts-importer#5]
After I press one of Examples in the left toc in https://www.exoego.net/scala-js-ts-importer/ , loading  starts and never stops.

![scala-js-ts-importer-webapp-bug](https://user-images.githubusercontent.com/26133249/61292847-478d6200-a80d-11e9-99c2-dbd856653da1.gif)

**Comment by exoego** [comment]
Importer works fine on 
* Chrome 75.0.3770.142（Official Build）
* Firefox 68.0

I saw similar error on older Chrome last year.
It was a bug in Chrome and seems fixed.
https://bugs.chromium.org/p/chromium/issues/detail?id=917215

Could you confirm that you are using the latest Chrome and the issue remains even.

**Comment by kencyke** [comment]
Thanks for your advice!

I encountered this bug on Google Chrome
* 72.0.3626.96（Official Build）

As you said, I try to update Google Chrome to
* 75.0.3770.142（Official Build） 

And then I confirm that your web-app works fine!

**Comment by exoego** [comment]
Closing since this is upstream (Chrome) issue and resolved.
